{% set version = "0.5.0" %}
{% set min_peer = "0.5" %}
{% set max_peer = "0.6" %}
{% set build_number = "0" %}

package:
  name: jupyter-wxyz
  version: {{ version }}

source:
  - folder: wxyz_core
    url: https://pypi.io/packages/source/w/wxyz_core/wxyz_core-{{ version }}.tar.gz
    sha256: 739e0d8cfb123ebbd917fd26f688a9844df979bda3756cdd38242c03d7963130
  - folder: wxyz_datagrid
    url: https://pypi.io/packages/source/w/wxyz_datagrid/wxyz_datagrid-{{ version }}.tar.gz
    sha256: d26108a3e966e5edcaabeda9fc96e9695549f945686b2cf17330fe34277150fc
  - folder: wxyz_dvcs
    url: https://pypi.io/packages/source/w/wxyz_dvcs/wxyz_dvcs-{{ version }}.tar.gz
    sha256: ac0937694363a1cbbb264aadfdc0d05ea424c367d87dbd0dc1086de087b96920
  - folder: wxyz_html
    url: https://pypi.io/packages/source/w/wxyz_html/wxyz_html-{{ version }}.tar.gz
    sha256: bd75e05f456fc29811cf05e51eb2d8a01e0ff4cf3a0ed6500b020a5c4735a0c2
  - folder: wxyz_json_e
    url: https://pypi.io/packages/source/w/wxyz_json_e/wxyz_json_e-{{ version }}.tar.gz
    sha256: a866160a9a9986c35e999e5a40fa63692e6ec0bb2763b1cdcee2a9769816897d
  - folder: wxyz_json_schema_form
    url: https://pypi.io/packages/source/w/wxyz_json_schema_form/wxyz_json_schema_form-{{ version }}.tar.gz
    sha256: 5c29bc87d2cbcdf0eab841c7de002341355e5cce7c23c121caa5b97394e6a5fe
  - folder: wxyz_jsonld
    url: https://pypi.io/packages/source/w/wxyz_jsonld/wxyz_jsonld-{{ version }}.tar.gz
    sha256: 06d3f7fdc8965dd87192a54d1066053866523b64f284cca79c2b274f771daac2
  - folder: wxyz_lab
    url: https://pypi.io/packages/source/w/wxyz_lab/wxyz_lab-{{ version }}.tar.gz
    sha256: 0777b42c8f6760d384b1f58107f29eb3aecb43f56e0fa409c525c00445db281d
  - folder: wxyz_svg
    url: https://pypi.io/packages/source/w/wxyz_svg/wxyz_svg-{{ version }}.tar.gz
    sha256: c81ca373ad4f4b9dc4eecf979e306a06c39df26e4ebd9e0d71297f9c5b4185c8
  - folder: wxyz_tpl_jinja
    url: https://pypi.io/packages/source/w/wxyz_tpl_jinja/wxyz_tpl_jinja-{{ version }}.tar.gz
    sha256: 4cb4851399f9dd90c2ceb756368e8bc3e1f416a429dafb1e046a602361944747
  - folder: wxyz_yaml
    url: https://pypi.io/packages/source/w/wxyz_yaml/wxyz_yaml-{{ version }}.tar.gz
    sha256: 856cb411fa54e1551ad41b45b21f93e746fa6208dd0092f5afa82f70629f5cb3

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo TBD

outputs:
  - name: wxyz_core
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_core && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - ipywidgets
        - jsonpointer
        - jupyterlab >=3,<4
        - python >=3.6
    test:
      requires:
        - pip
      imports:
        - wxyz.core
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON and evented transformations
      license: BSD-3-Clause
      license_file: wxyz_core/src/wxyz/core/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_datagrid
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_datagrid && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - pandas
        - python >=3.6
        - traittypes
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - wxyz_html >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.datagrid
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for the Lumino DataGrid
      license: BSD-3-Clause
      license_file: wxyz_datagrid/src/wxyz/datagrid/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_dvcs
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_dvcs && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - gitpython
        - python >=3.6
        - pyyaml
        - watchgod
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.dvcs
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for working with data in revision control
      license: BSD-3-Clause
      license_file: wxyz_dvcs/src/wxyz/dvcs/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_html
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_html && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.html
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for HTML5
      license: BSD-3-Clause
      license_file: wxyz_html/src/wxyz/html/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_json_e
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_json_e && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - json-e >=4.3,<5
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.json_e
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON-E
      license: BSD-3-Clause
      license_file: wxyz_json_e/src/wxyz/json_e/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_json_schema_form
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_json_schema_form && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.json_schema_form
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON Schema Form
      license: BSD-3-Clause
      license_file: wxyz_json_schema_form/src/wxyz/json_schema_form/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_jsonld
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_jsonld && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - pyld
    test:
      requires:
        - pip
      imports:
        - wxyz.jsonld
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON-LD
      license: BSD-3-Clause
      license_file: wxyz_jsonld/src/wxyz/jsonld/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_lab
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_lab && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.lab
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JupyterLab
      license: BSD-3-Clause
      license_file: wxyz_lab/src/wxyz/lab/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_svg
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_svg && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.svg
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for SVG
      license: BSD-3-Clause
      license_file: wxyz_svg/src/wxyz/svg/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_tpl_jinja
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_tpl_jinja && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - jinja2
    test:
      requires:
        - pip
      imports:
        - wxyz.tpl_jinja
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for Jinja2 templates
      license: BSD-3-Clause
      license_file: wxyz_tpl_jinja/src/wxyz/tpl_jinja/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_yaml
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_yaml && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - pyyaml
    test:
      requires:
        - pip
      imports:
        - wxyz.yaml
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for YAML
      license: BSD-3-Clause
      license_file: wxyz_yaml/src/wxyz/yaml/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

about:
  home: https://deathbeds.github.io/wxyz
  summary: experimental Jupyter widgets
  license: BSD-3-Clause
  license_file: wxyz_core/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
