{% set version = "0.4.2" %}
{% set min_peer = "0.4" %}
{% set max_peer = "0.5" %}
{% set build_number = "0" %}

package:
  name: jupyter-wxyz
  version: {{ version }}

source:
  - folder: wxyz_core
    url: https://pypi.io/packages/source/w/wxyz_core/wxyz_core-{{ version }}.tar.gz
    sha256: 40ea9334147f042739542159250619c03b42ccc594db7d76de2fb115e846ed6c
  - folder: wxyz_datagrid
    url: https://pypi.io/packages/source/w/wxyz_datagrid/wxyz_datagrid-{{ version }}.tar.gz
    sha256: 6396cbca5d41ba76e6b4ead0a312682900e52c32ab8697ed3fe27e07ff843a67
  - folder: wxyz_dvcs
    url: https://pypi.io/packages/source/w/wxyz_dvcs/wxyz_dvcs-{{ version }}.tar.gz
    sha256: bd659effd3c1d49a695ae2342f5a08464335f94dc3bed07df2c56dcced33fd10
  - folder: wxyz_html
    url: https://pypi.io/packages/source/w/wxyz_html/wxyz_html-{{ version }}.tar.gz
    sha256: 14550aceeeece784cdafab837a671874d97d64f497df078a3983384bc47a6282
  - folder: wxyz_json_e
    url: https://pypi.io/packages/source/w/wxyz_json_e/wxyz_json_e-{{ version }}.tar.gz
    sha256: 1f294a91f7d74e81da81ccb92cded375bc54e52818757a94055f6cb05bcd422b
  - folder: wxyz_json_schema_form
    url: https://pypi.io/packages/source/w/wxyz_json_schema_form/wxyz_json_schema_form-{{ version }}.tar.gz
    sha256: 851e13c37b8f8dd10078aa4197dee45a781e6b044fa4798b25f19b7a3e1f34cf
  - folder: wxyz_jsonld
    url: https://pypi.io/packages/source/w/wxyz_jsonld/wxyz_jsonld-{{ version }}.tar.gz
    sha256: 3f06d116904714e332d2a6fe1e63e6c41f3e55e02b08e65afb74b0f416b75243
  - folder: wxyz_lab
    url: https://pypi.io/packages/source/w/wxyz_lab/wxyz_lab-{{ version }}.tar.gz
    sha256: a268dd845ef1d41b1d26ae29050373a0b3cb1a49ffcb68d070417b5a634cc3a1
  - folder: wxyz_svg
    url: https://pypi.io/packages/source/w/wxyz_svg/wxyz_svg-{{ version }}.tar.gz
    sha256: 08f8be3e43acc0ee08cbdbbedc6e547959faee00d3fbd659c92d852d8c9aee70
  - folder: wxyz_tpl_jinja
    url: https://pypi.io/packages/source/w/wxyz_tpl_jinja/wxyz_tpl_jinja-{{ version }}.tar.gz
    sha256: 691cc6c3df050487b23aec7abcaf1ed5efb80da7e0eeada1e21c135b12221d6d
  - folder: wxyz_yaml
    url: https://pypi.io/packages/source/w/wxyz_yaml/wxyz_yaml-{{ version }}.tar.gz
    sha256: 0203400749a3b7675cfbac7b9404a0399749374bf938dac886d88c6a38a27d63

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo TBD

outputs:
  - name: wxyz_core
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_core && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - ipywidgets
        - jsonpointer
        - python >=3.6
    test:
      requires:
        - pip
      imports:
        - wxyz.core
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON and evented transformations
      license: BSD-3-Clause
      license_file: wxyz_core/src/wxyz/core/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_datagrid
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_datagrid && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - pandas
        - python >=3.6
        - traittypes
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - wxyz_html >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.datagrid
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for the Lumino DataGrid
      license: BSD-3-Clause
      license_file: wxyz_datagrid/src/wxyz/datagrid/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_dvcs
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_dvcs && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - gitpython
        - python >=3.6
        - pyyaml
        - watchgod
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.dvcs
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for working with data in revision control
      license: BSD-3-Clause
      license_file: wxyz_dvcs/src/wxyz/dvcs/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_html
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_html && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.html
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for HTML5
      license: BSD-3-Clause
      license_file: wxyz_html/src/wxyz/html/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_json_e
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_json_e && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - json-e >=4.3,<5
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.json_e
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON-E
      license: BSD-3-Clause
      license_file: wxyz_json_e/src/wxyz/json_e/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_json_schema_form
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_json_schema_form && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.json_schema_form
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON Schema Form
      license: BSD-3-Clause
      license_file: wxyz_json_schema_form/src/wxyz/json_schema_form/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_jsonld
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_jsonld && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - pyld
    test:
      requires:
        - pip
      imports:
        - wxyz.jsonld
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JSON-LD
      license: BSD-3-Clause
      license_file: wxyz_jsonld/src/wxyz/jsonld/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_lab
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_lab && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.lab
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for JupyterLab
      license: BSD-3-Clause
      license_file: wxyz_lab/src/wxyz/lab/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_svg
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_svg && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
    test:
      requires:
        - pip
      imports:
        - wxyz.svg
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for SVG
      license: BSD-3-Clause
      license_file: wxyz_svg/src/wxyz/svg/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_tpl_jinja
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_tpl_jinja && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - jinja2
    test:
      requires:
        - pip
      imports:
        - wxyz.tpl_jinja
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for Jinja2 templates
      license: BSD-3-Clause
      license_file: wxyz_tpl_jinja/src/wxyz/tpl_jinja/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

  - name: wxyz_yaml
    build:
      number: {{ build_number }}
      noarch: python
      script: cd wxyz_yaml && {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
        - wxyz_core >={{ min_peer }},<{{ max_peer }}
        - pyyaml
    test:
      requires:
        - pip
      imports:
        - wxyz.yaml
      commands:
        - pip check
    about:
      home: https://deathbeds.github.io/wxyz
      summary: experimental Jupyter widgets for YAML
      license: BSD-3-Clause
      license_file: wxyz_yaml/src/wxyz/yaml/js/LICENSE.txt
      dev_url: https://github.com/deathbeds/wxyz
      doc_url: https://deathbeds.github.io/wxyz
      doc_source_url: https://github.com/deathbeds/wxyz/tree/v{{ version }}/docs

about:
  home: https://deathbeds.github.io/wxyz
  summary: experimental Jupyter widgets
  license: BSD-3-Clause
  license_file: wxyz_core/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
